englix/models.py
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager, UserMixin
import enum

from app import db

class LevelType(enum.Enum):
    Intermadiate = 30
    Advanced = 60
    Fluent = 80

class RoleType(enum.Enum):
    Student = 1
    Admin = 0

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), nullable=False)
    email = db.Column(db.String(50), unique=True, nullable=False)
    password = db.Column(db.String(100), nullable=False)
    level_type = db.Column(db.Enum(LevelType), default = "Intermadiate")
    role_type = db.Column(db.Enum(RoleType), default = "Student")

    def __repr__(self):
        return '<name %r, email %r, password %r, id %r>' % (self.name, self.email, self.password, self.id)

class Lesson(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), unique=True, nullable=False)
    description = db.Column(db.String(1000), nullable=False)
    level_type = db.Column(db.Enum(LevelType))

    activities = db.relationship('Activity', backref='lesson', cascade="all,delete", lazy=True)

class ActivityType(enum.Enum):
    Video = "Video"
    AR = "AR"
    Text = "Text"

class Activity(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    lesson_id = db.Column(db.Integer, db.ForeignKey('lesson.id'), nullable=False)
    content_file = db.Column(db.String(1000), nullable=False)
    activity_type = db.Column(db.Enum(ActivityType))
    
    quizes = db.relationship('Quiz', backref='activity', cascade="all,delete", lazy=True)

class Quiz(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    content = db.Column(db.String(300), nullable=False)
    activity_id = db.Column(db.Integer, db.ForeignKey('activity.id'), nullable=False)
    answers = db.relationship('Answer', backref='quiz', cascade="all,delete", lazy=True)


class Answer(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    content = db.Column(db.String(300), nullable=False)
    answer_type = db.Column(db.Boolean, default=False, nullable=False)
    quiz_id = db.Column(db.Integer, db.ForeignKey('quiz.id'), nullable=False)

app.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView
from flask_login import LoginManager

db = SQLAlchemy()

def create_app():
    app = Flask(__name__)
    
    app.config['SECRET_KEY'] = "randomstring"
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///db.db'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = True
    db.init_app(app)

    from englix.views import englix
    app.register_blueprint(englix)

    
    from englix.models import User, Lesson, Activity, Quiz, Answer
    from englix.views import NewAdminIndexView, NewModelView

    admin = Admin(app, name='Englix', index_view=NewAdminIndexView())
    login_manager = LoginManager(app)
    
    login_manager.login_view = 'englix.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    admin.add_view(NewModelView(User, db.session))
    admin.add_view(NewModelView(Lesson, db.session))
    admin.add_view(NewModelView(Activity, db.session))
    admin.add_view(NewModelView(Quiz, db.session))
    admin.add_view(NewModelView(Answer, db.session))
    
    return app

if __name__ == "__main__":
    app = create_app()
    app.run(debug=True)

englix/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, abort
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, current_user, logout_user
from flask_admin import Admin, AdminIndexView
from flask_admin.contrib.sqla import ModelView
from sqlalchemy import func
from .models import User, Lesson, Activity, Quiz, Answer, RoleType
from app import db

englix = Blueprint('englix', __name__)

class NewModelView(ModelView):
    def is_accessible(self):
      if current_user.role_type == RoleType.Student: 
         return abort(404)
      else:
         return current_user.is_authenticated
    def inaccessible_callback(self, name, **kwargs):
        return abort(404)

class NewAdminIndexView(AdminIndexView):
    def is_accessible(self):
      if current_user.role_type == RoleType.Student: 
         return abort(404)
      else:
         return current_user.is_authenticated
    def inaccessible_callback(self, name, **kwargs):
        return abort(404)


# -------------------------------------------------------------------------------------- #

@englix.route('/login')
def login():
    return render_template('login.html')

@englix.route('/login', methods=['POST'])
def login_post():
   email = request.form['email']
   password = request.form['password']

   remember = True if request.form.get('remember') else False

   user = User.query.filter_by(email=email).first()

   if not user and not check_password_hash(user.password, password):
      return redirect(url_for('englix.login'))
   
   login_user(user, remember=remember)

   return redirect(url_for('englix.home'))

@englix.route('/signup') 
def signup():
    return render_template('cadastro.html')

@englix.route('/signup', methods=['POST'])
def signup_post():

   email = request.form['email']
   name = request.form['name']
   password = request.form['password']

   user = User.query.filter_by(email=email).first()

   if user:
      flash('Email adress already exists.')
      return redirect(url_for('englix.login'))

   new_user = User(email=email, name=name, password=generate_password_hash(password, method='sha256'))

   db.session.add(new_user)
   db.session.commit()
   
   return redirect(url_for('englix.login'))


@englix.route('/logout')
@login_required
def logout():
   logout_user()
   return redirect(url_for('englix.index'))


# -------------------------------------------------------------------------------------- #

@englix.route('/index')
def index():
   if current_user.is_authenticated:
      return redirect(url_for('englix.home'))
   return render_template('Index.html')

@englix.route('/home')
@login_required
def home():
   user_name = current_user.name
   user_level = current_user.level_type
   return render_template('home.html', lesson=Lesson.query.filter_by(level_type=user_level).order_by(func.random()).first(),name=user_name)

@englix.route('/lessons')
@login_required
def lessons(): 
   user_name = current_user.name
   user_level = current_user.level_type
   return render_template('lessons.html', lessons=Lesson.query.filter_by(level_type=user_level).all(), name=user_name)


@englix.route('/lesson/<int:lesson_id>')
@login_required
def lesson(lesson_id):
   user_name = current_user.name
   return render_template('lesson.html', lesson=Lesson.query.filter_by(id=lesson_id).first(), name=user_name)

@englix.route('/AR/<string:file>')
@login_required
def AR(file):
   user_name = current_user.name
   
   return render_template('/AR/'+file, name=user_name)

templates/Index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="../static/home.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="../static/index.css">

    <title>index Englix</title>
  </head>
  <body>
  <header>
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      
      <button class="navbar-toggler center" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon center"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto" style="display: flex" > 
          <a class="navbar-brand" href="{{ url_for('englix.index') }}">
            <img src="../static/img/home-24px.svg" width=40 height="28" class="d-inline-block align-top" alt="">
            Home
          </a>
          <!-- <a class="navbar-brand" href="#">
            <img src="../static/img/menu_book-24px.svg" width=40 height="28" class="d-inline-block align-top" alt="">
            Lessons
          </a>
          
          -->
        
        <a class="navbar-brand"  href="{{ url_for('englix.signup') }}" type="submit">
          <img src="../static/img/account_circle-24px.svg" id="sigin" width=40 height="28" class="d-inline-block align-top" alt="">
            Sing Up
        </a>
      </ul>
          <a class="navbar-brand" href="{{ url_for('englix.login') }}" type="submit">
          <img src="../static/img/supervised_user_circle-24px.svg" id="sigin" width=40 height="28" class="d-inline-block align-top" alt="">
            Log In
        </a>
<!--       
        <a class="navbar-brand" type="submit">
          <img src="../static/img/exit_to_app-24px.svg" width=40 height="28" class="d-inline-block align-top" alt="">
            Logout
        </a> -->
       
      </div>
    </nav>
  </header>
    
    <div class="container">
    <div class="Englix" >
    <a class="navbar-brand" id="title-1" href="#"><img src="../static/img/englix.png" style="width: 200px;"></a>
  </div>
    <div id="centro" class="jumbotron rounded bg-dark">
      <div class="col-md-6 px-0">
        <h1 class="display-4 font-bold">Upgrade your english skills with Englix!</h1>
        <h4 class="lead my-3">Learn watching clips from series and movies.</h4>
        <p class="lead mb-0"><a href="{{ url_for('englix.signup') }}" class="text-white font-weight-bold">Sign Up!</a></p>
       
      </div>
    </div>
    <br><br><br>



    <div class="row container marketing">
      <div class="row mx-auto" style="width: 1650px;">
      
        <div class="col-lg-4">

      
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 140x140"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"/><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg>
        <h2>Lessons</h2>
        <p>We make learning fun! Our activities contains clips from tv series and movies, it's a real-life experience.</p>
       
      </div><!-- /.col-lg-4 -->






      <div class="col-lg-4 ">
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 140x140"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"/><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg>
        <h2>Immersive Activities</h2>
        <p>Experience a new way of learning with Immersive Activities.</p>
        
      </div><!-- /.col-lg-4 -->
    </div>
    </div><!-- /.row -->
  </div>
</div>  
    

    <br>
    <br>
    <br>
    <br><br>
    <footer class="pt-4 my-md-5 pt-md-5 border-top" >
      <div class="row">
        <div class="col-12 col-md">
          <img class="mb-2" src="../assets/brand/bootstrap-solid.svg" alt="" width="24" height="24">
          
        </div>
        <div class="col-6 col-md">
          <h5>Staff</h5>
          <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="#">Júlia Vitória</a></li>
            <li><a class="text-muted" href="#">Felipe Ramos</a></li>
            <li><a class="text-muted" href="#">Bruno Eduardo</a></li>
            <li><a class="text-muted" href="#">Alan Ricardo</a></li>
            
          </ul>
        </div>
        <div class="col-6 col-md">
          <h5>Github</h5>
          <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="https://github.com/juliavpaiva">juliavpaiva</a></li>
            <li><a class="text-muted" href="https://github.com/felphlk">felphlk</a></li>
            <li><a class="text-muted" href="https://github.com/brunneves">brunneves</a></li>
            <li><a class="text-muted" href="https://github.com/AlanRicardoS">alanricardos</a></li>
          </ul>
        </div>
        
      </div>
    </footer>
    </body>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script>
      $(function () {
        var nua = navigator.userAgent
        var isAndroid = (nua.indexOf('Mozilla/5.0') > -1 && nua.indexOf('Android ') > -1 && nua.indexOf('AppleWebKit') > -1 && nua.indexOf('Chrome') === -1)
        if (isAndroid) {
          $('select.form-control').removeClass('form-control').css('width', '100%')
        }
      })
      </script>
  
</html>

templates/activities/lesson1_activity2.html
<div id="content">Watch the video bellow to see how phrasal verbs can be used on a real situation</div>
<br>
<iframe width="560" height="315" src="https://www.youtube.com/embed/Vmb1tqYqyII" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
<br><br>

templates/activities/lesson1_activity3.html
<div id="content">Look at the 360° photo, you can click and drag your mouse to look around, pay attention to the audio and complete the sentences correctly:</div>
<br>
<a href="{{ url_for('englix.AR', file='/RA.html' ) }}" class="btn" style="color: white; background-color: rgb(229,9,20);" target="_blank" >Go to Immersive Activity</a>
<br><br>
                  

templates/home.html
<!DOCTYPE html>

<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="../static/home.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">


    <title>Home Englix</title>
  </head>
  <body>
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      
      <button class="navbar-toggler center" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon center"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto" style="display: flex" > 
          <a href="{{ url_for('englix.home') }}" class="navbar-brand">
            <img src="../static/img/home-24px.svg" width=40 height="28" class="d-inline-block align-top" alt="">
            Home
          </a>
          <a class="navbar-brand" href="{{ url_for('englix.lessons') }}">
            <img src="../static/img/menu_book-24px.svg" width=40 height="28" class="d-inline-block align-top" alt="">
            Lessons
          </a>
          <a class="navbar-brand" href="{{ url_for('englix.lessons') }}">
            <img src="../static/img/card_membership-24px.svg" width=40 height="28" class="d-inline-block align-top" alt="">
            test your level
          </a>
          
          </ul>
          <ul class="navbar-nav " style="display: flex" > 
          <a class="navbar-brand " type="submit">
          <img src="../static/img/supervised_user_circle-24px.svg" width=40 height="28" class="d-inline-block align-top" alt="">
            {{ name }}
        </a>
        <a href="{{ url_for('englix.logout') }}" class="navbar-brand" type="submit">
          <img src="../static/img/exit_to_app-24px.svg" width=40 height="28" class="d-inline-block align-top" alt="">
            Logout
        </a>
      </ul>
      </div>
    </nav>
<div class="container">
      <div style="width: 20%">
    <a class="navbar-brand" id="title-1" href="#"><img src="../static/img/englix.png" style="width: 200px;"></a>
  </div>
    <div id="centro" class="jumbotron rounded bg-dark">
      <div class="col-md-6 px-0">
        <h1 class="display-4 font-bold">Check out this Lesson!</h1>
        <h4 class="lead my-3">Lesson {{ lesson.id }} - {{ lesson.name }} <br> {{ lesson.description }}</h4>
        <p class="lead mb-0"><a href="{{ url_for('englix.lesson', lesson_id=lesson.id) }}" class="text-white font-weight-bold">Go to Lesson</a></p>
       
      </div>
    </div>
    <div class="row mb-2">
      <div id="centro1" class="col-md-6">
        <div id="centro1" class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
          <div class="col p-4 d-flex flex-column position-static">
            <strong class="d-inline-block mb-2" style="color: rgb(229,9,20);">Lessons</strong>
            <h3 class="mb-0">Your Lessons are waiting for you</h3>
            
           <br>
            <button type="button" class="btn" style="background-color: rgb(229,9,20);"><a href="{{ url_for('englix.lessons') }}" class="stretched-link text-light">Go to Lessons list</a></button>
          </div>
          <div class="col-auto d-none d-lg-block">
            <svg class="bd-placeholder-img " width="200" height="250"  xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
          </div>
        </div>
      </div>
      <div id="centro1" class="col-md-6">
        <div id="centro1" class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
          <div class="col p-4 d-flex flex-column position-static">
            <strong class="d-inline-block mb-2 " style="color: rgb(229,9,20);">Immersive Activities</strong>
            
            <h3 class="mb-0">Here at ENGLIX we want you to have fun!</h3>
            <br>
            <button type="button" class="btn" style="background-color: rgb(229,9,20);"><a href="#" class="stretched-link text-light">Find out more</a></button>
          </div>
          <div class="col-auto d-none d-lg-block">
            <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
          </div>
        </div>
      </div>
    </div>
    <div><br><br></div>
  </div>  

    
  <br>
  <br>
  <br>
  <br><br>

  <footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
      <div class="col-12 col-md">
        <img class="mb-2" src="../assets/brand/bootstrap-solid.svg" alt="" width="24" height="24">
        
      </div>
      <div class="col-6 col-md">
        <h5>Staff</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Júlia Vitória</a></li>
          <li><a class="text-muted" href="#">Felipe Ramos</a></li>
          <li><a class="text-muted" href="#">Bruno Eduardo</a></li>
          <li><a class="text-muted" href="#">Alan Ricardo</a></li>
          
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Github</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="https://github.com/juliavpaiva">juliavpaiva</a></li>
          <li><a class="text-muted" href="https://github.com/felphlk">felphlk</a></li>
          <li><a class="text-muted" href="https://github.com/brunneves">brunneves</a></li>
          <li><a class="text-muted" href="https://github.com/AlanRicardoS">alanricardos</a></li>
        </ul>
      </div>
      
  </div>
  </footer>
    </body>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script>
      $(function () {
        var nua = navigator.userAgent
        var isAndroid = (nua.indexOf('Mozilla/5.0') > -1 && nua.indexOf('Android ') > -1 && nua.indexOf('AppleWebKit') > -1 && nua.indexOf('Chrome') === -1)
        if (isAndroid) {
          $('select.form-control').removeClass('form-control').css('width', '100%')
        }
      })
      </script>
  
</html>

templates/lessons.html
<!DOCTYPE html>

<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="../static/lesson.css">
    <title>Lessons</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      
      <button class="navbar-toggler center" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon center"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto" style="display: flex" > 
          <a href="{{ url_for('englix.home') }}" class="navbar-brand">
            <img src="../static/img/home-24px.svg" width=40 height="28" class="d-inline-block align-top" alt="">
            Home
          </a>
          <a class="navbar-brand" href="{{ url_for('englix.lessons') }}">
            <img src="../static/img/menu_book-24px.svg" width=40 height="28" class="d-inline-block align-top" alt="">
            Lessons
          </a>
          <a class="navbar-brand" href="{{ url_for('englix.lessons') }}">
            <img src="../static/img/card_membership-24px.svg" width=40 height="28" class="d-inline-block align-top" alt="">
            test your level
          </a>
          
          </ul>
          <ul class="navbar-nav " style="display: flex" > 
          <a class="navbar-brand " type="submit">
          <img src="../static/img/supervised_user_circle-24px.svg" width=40 height="28" class="d-inline-block align-top" alt="">
            {{ name }}
        </a>
        <a href="{{ url_for('englix.logout') }}" class="navbar-brand" type="submit">
          <img src="../static/img/exit_to_app-24px.svg" width=40 height="28" class="d-inline-block align-top" alt="">
            Logout
        </a>
      </ul>
      </div>
    </nav>
      
          
        <div class="container">
            
            <div class="Englix" >
            <a class="navbar-brand" id="title-1" href="#"><img src="../static/img/englix.png" style="width: 200px;"></a>
          </div>
       <br><br><br>
        
       {% if lessons %}
          
          {% for lesson in lessons %}
            <div class="accordion" id="accordionExample">
              <div class="card">
                <div class="card-header" id="heading{{lesson.id}}">
                  <h2 class="mb-0">
                    
                    <button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" style="padding: 1px 2px ;" data-target="#collapse{{lesson.id}}" aria-expanded="true" aria-controls="collapse{{lesson.id}}">
                      <b style="font-size: 25px; color: rgb(229,9,20);"> Lesson {{ lesson.id }} - {{ lesson.name }} </b> <img class="float-right" src="../static/img/done-24px.svg" alt="20x20">
                    </button>
                  </h2>
                </div>
            
                <div id="collapse{{lesson.id}}" class="collapse" aria-labelledby="heading{{lesson.id}}" data-parent="#accordionExample">
                  <div class="card-body">
                    <h5 class="card-text">{{ lesson.description }}</h5>
                    <a href="{{ url_for('englix.lesson', lesson_id=lesson.id) }}" class="btn" style="color: white; background-color: rgb(229,9,20);" >Go to Lesson</a>
            
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}
          
        {% else %}
            
          <h5 class="card-text">No lessons available</h5>
        {% endif %}
          
        <footer class="pt-4 my-md-5 pt-md-5 border-top">
          <div class="row">
            <div class="col-12 col-md">
              <img class="mb-2" src="../assets/brand/bootstrap-solid.svg" alt="" width="24" height="24">
              
            </div>
            <div class="col-6 col-md">
              <h5>Staff</h5>
              <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Júlia Vitória</a></li>
                <li><a class="text-muted" href="#">Felipe Ramos</a></li>
                <li><a class="text-muted" href="#">Bruno Eduardo</a></li>
                <li><a class="text-muted" href="#">Alan Ricardo</a></li>
                
              </ul>
            </div>
            <div class="col-6 col-md">
              <h5>Github</h5>
              <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="https://github.com/juliavpaiva">juliavpaiva</a></li>
                <li><a class="text-muted" href="https://github.com/felphlk">felphlk</a></li>
                <li><a class="text-muted" href="https://github.com/brunneves">brunneves</a></li>
                <li><a class="text-muted" href="https://github.com/AlanRicardoS">alanricardos</a></li>
              </ul>
            </div>
            
          </div>
        </footer>
   
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>